"""schema inicial

Revision ID: 55da2fa5e05c
Revises: 
Create Date: 2026-09-17 17:42:03.997869
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '55da2fa5e05c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_produto',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias_produto')),
    sa.UniqueConstraint('nome', name=op.f('uq_categorias_produto_nome'))
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departamentos')),
    sa.UniqueConstraint('nome', name=op.f('uq_departamentos_nome'))
    )
    op.create_table('empresas',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codemp', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas')),
    sa.UniqueConstraint('codemp', name=op.f('uq_empresas_codemp'))
    )
    op.create_table('tentativas_login',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('tentativas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('codigo', name=op.f('pk_tentativas_login'))
    )
    op.create_table('colaboradores',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome_completo', sa.String(length=160), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('codparc', sa.Integer(), nullable=False),
    sa.Column('vinculo', sa.String(length=10), server_default='clt', nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('papel', sa.String(length=20), server_default='colaborador', nullable=False),
    sa.Column('departamento_id', sa.Uuid(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('senha_provisoria', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(vinculo = 'clt' and matricula is not null) or (vinculo = 'pj' and matricula is null)", name=op.f('ck_colaboradores_matricula_conforme_vinculo')),
    sa.CheckConstraint("papel in ('colaborador', 'refeitorio', 'admin')", name=op.f('ck_colaboradores_papel_valido')),
    sa.CheckConstraint("vinculo in ('clt', 'pj')", name=op.f('ck_colaboradores_vinculo_valido')),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], name=op.f('fk_colaboradores_departamento_id_departamentos')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_colaboradores_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colaboradores')),
    sa.UniqueConstraint('empresa_id', 'matricula', name='uq_colaboradores_empresa_matricula')
    )
    op.create_index('ix_colaboradores_ativo_nome', 'colaboradores', ['ativo', 'nome_completo'], unique=False)
    op.create_index(op.f('ix_colaboradores_codigo'), 'colaboradores', ['codigo'], unique=True)
    op.create_index(op.f('ix_colaboradores_codparc'), 'colaboradores', ['codparc'], unique=True)
    op.create_table('produtos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('estoque', sa.Integer(), server_default='0', nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estoque >= 0', name=op.f('ck_produtos_estoque_nao_negativo')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_produto.id'], name=op.f('fk_produtos_categoria_id_categorias_produto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produtos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_produtos_codigo'))
    )
    op.create_table('ajustes_estoque',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.Column('criado_por', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo in ('entrada', 'baixa')", name=op.f('ck_ajustes_estoque_tipo_valido')),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_ajustes_estoque_quantidade_positiva')),
    sa.ForeignKeyConstraint(['criado_por'], ['colaboradores.id'], name=op.f('fk_ajustes_estoque_criado_por_colaboradores')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_ajustes_estoque_produto_id_produtos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ajustes_estoque'))
    )
    op.create_index('ix_ajustes_estoque_produto_criado', 'ajustes_estoque', ['produto_id', 'criado_em'], unique=False)
    op.create_table('exportacoes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='aberta', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.Uuid(), nullable=True),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exportado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arquivo_caminho', sa.String(length=500), nullable=True),
    sa.Column('total_registros', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.CheckConstraint("status in ('aberta', 'fechada', 'exportada', 'descartada')", name=op.f('ck_exportacoes_status_valido')),
    sa.ForeignKeyConstraint(['criado_por'], ['colaboradores.id'], name=op.f('fk_exportacoes_criado_por_colaboradores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exportacoes'))
    )
    op.create_table('log_acesso',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=160), nullable=True),
    sa.Column('evento', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.String(length=60), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('correlacao_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("evento in ('login_ok', 'login_negado', 'bloqueado', 'logout', 'senha_trocada', 'senha_solicitada')", name=op.f('ck_log_acesso_evento_valido')),
    sa.ForeignKeyConstraint(['usuario_id'], ['colaboradores.id'], name=op.f('fk_log_acesso_usuario_id_colaboradores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_acesso'))
    )
    op.create_index('ix_log_acesso_codigo_criado', 'log_acesso', ['codigo', 'criado_em'], unique=False)
    op.create_index('ix_log_acesso_criado', 'log_acesso', ['criado_em'], unique=False)
    op.create_index('ix_log_acesso_evento_criado', 'log_acesso', ['evento', 'criado_em'], unique=False)
    op.create_index('ix_log_acesso_ip_criado', 'log_acesso', ['ip', 'criado_em'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_codigo', sa.String(length=40), nullable=False),
    sa.Column('usuario_nome', sa.String(length=160), nullable=False),
    sa.Column('usuario_papel', sa.String(length=20), nullable=False),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('entidade', sa.String(length=40), nullable=False),
    sa.Column('entidade_id', sa.Uuid(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('dados_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('correlacao_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['colaboradores.id'], name=op.f('fk_log_auditoria_usuario_id_colaboradores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_auditoria'))
    )
    op.create_index('ix_log_auditoria_acao_criado', 'log_auditoria', ['acao', 'criado_em'], unique=False)
    op.create_index('ix_log_auditoria_codigo_criado', 'log_auditoria', ['usuario_codigo', 'criado_em'], unique=False)
    op.create_index('ix_log_auditoria_criado', 'log_auditoria', ['criado_em'], unique=False)
    op.create_index('ix_log_auditoria_entidade', 'log_auditoria', ['entidade', 'entidade_id', 'criado_em'], unique=False)
    op.create_index('ix_log_auditoria_usuario_criado', 'log_auditoria', ['usuario_id', 'criado_em'], unique=False)
    op.create_table('precos_almoco',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fim', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_por', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['colaboradores.id'], name=op.f('fk_precos_almoco_criado_por_colaboradores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_precos_almoco'))
    )
    op.create_index(op.f('ix_precos_almoco_vigencia_inicio'), 'precos_almoco', ['vigencia_inicio'], unique=False)
    op.create_table('solicitacoes_senha',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nome_informado', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='aberta', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atendido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atendido_por', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status in ('aberta', 'atendida', 'descartada')", name=op.f('ck_solicitacoes_senha_status_valido')),
    sa.ForeignKeyConstraint(['atendido_por'], ['colaboradores.id'], name=op.f('fk_solicitacoes_senha_atendido_por_colaboradores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solicitacoes_senha'))
    )
    op.create_index('ix_solicitacoes_senha_status_criado', 'solicitacoes_senha', ['status', 'criado_em'], unique=False)
    op.create_table('almocos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('colaborador_id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('vinculo', sa.String(length=10), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=True),
    sa.Column('codigo_barras', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('origem', sa.String(length=20), server_default='totem', nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmado_por', sa.Uuid(), nullable=True),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('exportado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("origem in ('totem', 'manual')", name=op.f('ck_almocos_origem_valida')),
    sa.CheckConstraint("status in ('pendente', 'confirmado', 'expirado', 'cancelado')", name=op.f('ck_almocos_status_valido')),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], name=op.f('fk_almocos_colaborador_id_colaboradores')),
    sa.ForeignKeyConstraint(['confirmado_por'], ['colaboradores.id'], name=op.f('fk_almocos_confirmado_por_colaboradores')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_almocos_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['lote_id'], ['exportacoes.id'], name=op.f('fk_almocos_lote_id_exportacoes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_almocos')),
    sa.UniqueConstraint('codigo_barras', name=op.f('uq_almocos_codigo_barras'))
    )
    op.create_index('ix_almocos_colaborador_criado', 'almocos', ['colaborador_id', 'criado_em'], unique=False)
    op.create_index('ix_almocos_status_criado', 'almocos', ['status', 'criado_em'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('colaborador_id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('vinculo', sa.String(length=10), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('codigo_retirada', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entregue_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entregue_por', sa.Uuid(), nullable=True),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=300), nullable=True),
    sa.Column('lote_id', sa.Uuid(), nullable=True),
    sa.Column('exportado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pendente', 'entregue', 'cancelado')", name=op.f('ck_pedidos_status_valido')),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], name=op.f('fk_pedidos_colaborador_id_colaboradores')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_pedidos_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['entregue_por'], ['colaboradores.id'], name=op.f('fk_pedidos_entregue_por_colaboradores')),
    sa.ForeignKeyConstraint(['lote_id'], ['exportacoes.id'], name=op.f('fk_pedidos_lote_id_exportacoes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedidos'))
    )
    op.create_index('ix_pedidos_colaborador_criado', 'pedidos', ['colaborador_id', 'criado_em'], unique=False)
    op.create_index('ix_pedidos_status_criado', 'pedidos', ['status', 'criado_em'], unique=False)
    op.create_table('itens_pedido',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=True),
    sa.Column('nome_produto', sa.String(length=160), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_itens_pedido_quantidade_positiva')),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('fk_itens_pedido_pedido_id_pedidos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_itens_pedido_produto_id_produtos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itens_pedido'))
    )
    # ### end Alembic commands ###

    # Índices únicos parciais — escritos à mão, o autogenerate não os produz.
    # Cada um carrega uma regra de negócio. Removê-los não quebra nada
    # visivelmente: a falha só aparece com dois usuários agindo ao mesmo tempo.

    # Um almoço ativo por colaborador por dia, no fuso de São Paulo.
    op.execute(
        """
        create unique index almocos_um_por_dia
          on almocos (
            colaborador_id,
            ((criado_em at time zone 'America/Sao_Paulo')::date)
          )
          where status in ('pendente', 'confirmado')
        """
    )

    # Código de retirada único entre os pedidos ainda pendentes. Códigos podem
    # ser reaproveitados depois que o pedido é entregue ou cancelado.
    op.execute(
        """
        create unique index pedidos_codigo_retirada_pendente_uk
          on pedidos (codigo_retirada)
          where status = 'pendente'
        """
    )

    # Uma competência ativa por vez. Descartadas não contam, para permitir
    # refazer um fechamento que saiu errado.
    op.execute(
        """
        create unique index exportacoes_competencia_ativa_uk
          on exportacoes (competencia)
          where status <> 'descartada'
        """
    )


def downgrade() -> None:
    op.execute("drop index if exists exportacoes_competencia_ativa_uk")
    op.execute("drop index if exists pedidos_codigo_retirada_pendente_uk")
    op.execute("drop index if exists almocos_um_por_dia")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_index('ix_pedidos_status_criado', table_name='pedidos')
    op.drop_index('ix_pedidos_colaborador_criado', table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index('ix_almocos_status_criado', table_name='almocos')
    op.drop_index('ix_almocos_colaborador_criado', table_name='almocos')
    op.drop_table('almocos')
    op.drop_index('ix_solicitacoes_senha_status_criado', table_name='solicitacoes_senha')
    op.drop_table('solicitacoes_senha')
    op.drop_index(op.f('ix_precos_almoco_vigencia_inicio'), table_name='precos_almoco')
    op.drop_table('precos_almoco')
    op.drop_index('ix_log_auditoria_usuario_criado', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_entidade', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_criado', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_codigo_criado', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_acao_criado', table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index('ix_log_acesso_ip_criado', table_name='log_acesso')
    op.drop_index('ix_log_acesso_evento_criado', table_name='log_acesso')
    op.drop_index('ix_log_acesso_criado', table_name='log_acesso')
    op.drop_index('ix_log_acesso_codigo_criado', table_name='log_acesso')
    op.drop_table('log_acesso')
    op.drop_table('exportacoes')
    op.drop_index('ix_ajustes_estoque_produto_criado', table_name='ajustes_estoque')
    op.drop_table('ajustes_estoque')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_colaboradores_codparc'), table_name='colaboradores')
    op.drop_index(op.f('ix_colaboradores_codigo'), table_name='colaboradores')
    op.drop_index('ix_colaboradores_ativo_nome', table_name='colaboradores')
    op.drop_table('colaboradores')
    op.drop_table('tentativas_login')
    op.drop_table('empresas')
    op.drop_table('departamentos')
    op.drop_table('categorias_produto')
    # ### end Alembic commands ###
