"""versao de sessao no lugar do corte por data

Revision ID: 94084aae2586
Revises: 8b7c6d5e4f3a
Create Date: 2026-09-18 18:48:47.151869
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '94084aae2586'
down_revision: str | None = '8b7c6d5e4f3a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colaboradores', sa.Column('sessao_versao', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('colaboradores', 'tokens_validos_apos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colaboradores', sa.Column('tokens_validos_apos', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('colaboradores', 'sessao_versao')
    # ### end Alembic commands ###
