"""Erros previstos da aplicação, agrupados por natureza.

    acesso     401/403/429  quem é e o que pode
    validacao  422          o que foi enviado está errado
    recursos   404          o registro pedido não existe
    negocio    409          o envio está certo, o estado atual impede
"""

from app.excecoes.acesso import (
    AcessoBloqueado,
    ColaboradorInativo,
    CredenciaisInvalidas,
    NaoAutenticado,
    SemPermissao,
    SenhaAtualIncorreta,
    SenhaFraca,
    SenhaProvisoriaExpirada,
    SenhaProvisoriaPendente,
    SenhaRepetida,
)
from app.excecoes.base import Conflito, DadosInvalidos, ErroDaAplicacao, NaoEncontrado
from app.excecoes.negocio import (
    AlmocoExpirado,
    AlmocoJaConfirmado,
    AlmocoJaGeradoHoje,
    AlmocoNaoConfirmado,
    AutoInativacao,
    CadastroDuplicado,
    CarrinhoVazio,
    CodempDuplicado,
    CodigoDeBarrasInvalido,
    CodigoDuplicado,
    CodigoRetiradaIndisponivel,
    CodparcDuplicado,
    ColaboradorSemCodparc,
    CompetenciaFechada,
    DepartamentoDuplicado,
    EmpresaComColaboradores,
    EstoqueInsuficiente,
    MatriculaDuplicada,
    PedidoNaoPendente,
    ProdutoIndisponivel,
    SolicitacaoJaTratada,
)
from app.excecoes.recursos import (
    AlmocoNaoEncontrado,
    CategoriaNaoEncontrada,
    ColaboradorNaoEncontrado,
    DepartamentoNaoEncontrado,
    EmpresaNaoEncontrada,
    ProdutoNaoEncontrado,
    SolicitacaoNaoEncontrada,
)
from app.excecoes.validacao import (
    CodempInvalido,
    CompetenciaInvalida,
    FotoUrlLonga,
    ImportacaoGrandeDemais,
    ImportacaoVazia,
    MatriculaNaoPermitida,
    MatriculaObrigatoria,
    NomeObrigatorio,
    PapelInvalido,
    QuantidadeInvalida,
    TipoDeAjusteInvalido,
    ValorNegativo,
    VinculoInvalido,
)

__all__ = [
    "AcessoBloqueado",
    "AlmocoExpirado",
    "AlmocoJaConfirmado",
    "AlmocoJaGeradoHoje",
    "AlmocoNaoConfirmado",
    "AlmocoNaoEncontrado",
    "AutoInativacao",
    "CadastroDuplicado",
    "CarrinhoVazio",
    "CategoriaNaoEncontrada",
    "CodempDuplicado",
    "CodempInvalido",
    "CodigoDeBarrasInvalido",
    "CodigoDuplicado",
    "CodigoRetiradaIndisponivel",
    "CodparcDuplicado",
    "ColaboradorInativo",
    "ColaboradorNaoEncontrado",
    "ColaboradorSemCodparc",
    "CompetenciaFechada",
    "CompetenciaInvalida",
    "Conflito",
    "CredenciaisInvalidas",
    "DadosInvalidos",
    "DepartamentoDuplicado",
    "DepartamentoNaoEncontrado",
    "EmpresaComColaboradores",
    "EmpresaNaoEncontrada",
    "ErroDaAplicacao",
    "EstoqueInsuficiente",
    "FotoUrlLonga",
    "ImportacaoGrandeDemais",
    "ImportacaoVazia",
    "MatriculaDuplicada",
    "MatriculaNaoPermitida",
    "MatriculaObrigatoria",
    "NaoAutenticado",
    "NaoEncontrado",
    "NomeObrigatorio",
    "PapelInvalido",
    "PedidoNaoPendente",
    "ProdutoIndisponivel",
    "ProdutoNaoEncontrado",
    "QuantidadeInvalida",
    "SemPermissao",
    "SenhaAtualIncorreta",
    "SenhaFraca",
    "SenhaProvisoriaExpirada",
    "SenhaProvisoriaPendente",
    "SenhaRepetida",
    "SolicitacaoJaTratada",
    "SolicitacaoNaoEncontrada",
    "TipoDeAjusteInvalido",
    "ValorNegativo",
    "VinculoInvalido",
]
