/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlmocoRouteImport } from './routes/almoco'
import { Route as ColaboradorRouteImport } from './routes/colaborador'
import { Route as ConsumoRouteImport } from './routes/consumo'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlmocosRouteImport } from './routes/admin.almocos'
import { Route as AdminColaboradoresRouteImport } from './routes/admin.colaboradores'
import { Route as AdminEntregasRouteImport } from './routes/admin.entregas'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminVendasRouteImport } from './routes/admin.vendas'
import { Route as LojaSucessoPedidoIdRouteImport } from './routes/loja_.sucesso.$pedidoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmocoRoute = AlmocoRouteImport.update({
  id: '/almoco',
  path: '/almoco',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorRoute = ColaboradorRouteImport.update({
  id: '/colaborador',
  path: '/colaborador',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumoRoute = ConsumoRouteImport.update({
  id: '/consumo',
  path: '/consumo',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlmocosRoute = AdminAlmocosRouteImport.update({
  id: '/almocos',
  path: '/almocos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColaboradoresRoute = AdminColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregasRoute = AdminEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendasRoute = AdminVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSucessoPedidoIdRoute = LojaSucessoPedidoIdRouteImport.update({
  id: '/loja_/sucesso/$pedidoId',
  path: '/loja/sucesso/$pedidoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/almoco': typeof AlmocoRoute
  '/colaborador': typeof ColaboradorRoute
  '/consumo': typeof ConsumoRoute
  '/loja': typeof LojaRoute
  '/painel': typeof PainelRoute
  '/admin/almocos': typeof AdminAlmocosRoute
  '/admin/colaboradores': typeof AdminColaboradoresRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/loja/sucesso/$pedidoId': typeof LojaSucessoPedidoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/almoco': typeof AlmocoRoute
  '/colaborador': typeof ColaboradorRoute
  '/consumo': typeof ConsumoRoute
  '/loja': typeof LojaRoute
  '/painel': typeof PainelRoute
  '/admin/almocos': typeof AdminAlmocosRoute
  '/admin/colaboradores': typeof AdminColaboradoresRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin': typeof AdminIndexRoute
  '/loja/sucesso/$pedidoId': typeof LojaSucessoPedidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/almoco': typeof AlmocoRoute
  '/colaborador': typeof ColaboradorRoute
  '/consumo': typeof ConsumoRoute
  '/loja': typeof LojaRoute
  '/painel': typeof PainelRoute
  '/admin/almocos': typeof AdminAlmocosRoute
  '/admin/colaboradores': typeof AdminColaboradoresRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/loja_/sucesso/$pedidoId': typeof LojaSucessoPedidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/almoco'
    | '/colaborador'
    | '/consumo'
    | '/loja'
    | '/painel'
    | '/admin/almocos'
    | '/admin/colaboradores'
    | '/admin/entregas'
    | '/admin/estoque'
    | '/admin/vendas'
    | '/admin/'
    | '/loja/sucesso/$pedidoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/almoco'
    | '/colaborador'
    | '/consumo'
    | '/loja'
    | '/painel'
    | '/admin/almocos'
    | '/admin/colaboradores'
    | '/admin/entregas'
    | '/admin/estoque'
    | '/admin/vendas'
    | '/admin'
    | '/loja/sucesso/$pedidoId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/almoco'
    | '/colaborador'
    | '/consumo'
    | '/loja'
    | '/painel'
    | '/admin/almocos'
    | '/admin/colaboradores'
    | '/admin/entregas'
    | '/admin/estoque'
    | '/admin/vendas'
    | '/admin/'
    | '/loja_/sucesso/$pedidoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlmocoRoute: typeof AlmocoRoute
  ColaboradorRoute: typeof ColaboradorRoute
  ConsumoRoute: typeof ConsumoRoute
  LojaRoute: typeof LojaRoute
  PainelRoute: typeof PainelRoute
  LojaSucessoPedidoIdRoute: typeof LojaSucessoPedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almoco': {
      id: '/almoco'
      path: '/almoco'
      fullPath: '/almoco'
      preLoaderRoute: typeof AlmocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador': {
      id: '/colaborador'
      path: '/colaborador'
      fullPath: '/colaborador'
      preLoaderRoute: typeof ColaboradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumo': {
      id: '/consumo'
      path: '/consumo'
      fullPath: '/consumo'
      preLoaderRoute: typeof ConsumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/almocos': {
      id: '/admin/almocos'
      path: '/almocos'
      fullPath: '/admin/almocos'
      preLoaderRoute: typeof AdminAlmocosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colaboradores': {
      id: '/admin/colaboradores'
      path: '/colaboradores'
      fullPath: '/admin/colaboradores'
      preLoaderRoute: typeof AdminColaboradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregas': {
      id: '/admin/entregas'
      path: '/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AdminEntregasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendas': {
      id: '/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AdminVendasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja_/sucesso/$pedidoId': {
      id: '/loja_/sucesso/$pedidoId'
      path: '/loja/sucesso/$pedidoId'
      fullPath: '/loja/sucesso/$pedidoId'
      preLoaderRoute: typeof LojaSucessoPedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAlmocosRoute: typeof AdminAlmocosRoute
  AdminColaboradoresRoute: typeof AdminColaboradoresRoute
  AdminEntregasRoute: typeof AdminEntregasRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminVendasRoute: typeof AdminVendasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlmocosRoute: AdminAlmocosRoute,
  AdminColaboradoresRoute: AdminColaboradoresRoute,
  AdminEntregasRoute: AdminEntregasRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminVendasRoute: AdminVendasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlmocoRoute: AlmocoRoute,
  ColaboradorRoute: ColaboradorRoute,
  ConsumoRoute: ConsumoRoute,
  LojaRoute: LojaRoute,
  PainelRoute: PainelRoute,
  LojaSucessoPedidoIdRoute: LojaSucessoPedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
